name: lara

options:
  bundleIdPrefix: com.roooot
  deploymentTarget:
    iOS: 17.0

targets:
  Lara:
    type: application
    platform: iOS

    sources:
      - path: lara

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.roooot.lara
        INFOPLIST_FILE: lara/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: lara/lara-Bridging-Header.h
        LIBRARY_SEARCH_PATHS: $(inherited) $(SRCROOT)/lib
        OTHER_LDFLAGS: $(inherited) -lxpf -lgrabkernel -lmuffinstore

    dependencies:
      - sdk: UIKit.framework
      - sdk: Foundation.framework
